### ISSUE TITLE
To Base64URL or to Base58, that is the question

### ISSUE THREAD

**Issue by csuwildcat** [decentralized-identity/confidential-storage#119]
Per nudge from @OR13, we should probably decide on an encoding to use across the spec.

**Comment by OR13** [comment]
I'm dealing with versions of this everywhere thanks to the popularity of base58btc now, and the popularity of base64url before..... IMO, it totally sucks to have an API that requires both, so we should pick one...

Since IPFS and DID Core are newer and use base58btc... I suggest we just use that, and say fairwell to old and sad base64url without padding....

**Comment by OR13** [comment]
All in favor of base58btc anywhere we can?

**Comment by dlongley** [comment]
I'm in favor of base58btc where we can ... but I'm not sure we can eliminate base64url everywhere... certainly not from other specs that we depend on; so I don't expect implementations to be able to get away with implementing just one.

**Comment by OR13** [comment]
of course we can't change JOSE, but we can choose to never use base64url again.
